name: Run Python Script

on:
  schedule:
    - cron: '42 21 * * *' # Runs every day at midnight UTC
  push:
    branches:
      - main
      - test
#
jobs:
  invest_sma_alert:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'  # You can specify the Python version here
      - name: 1list files
        run: ls -l
      - name: 2get current directory
        run: pwd
      - name: 3list parrent
        run: ls -l ..
      - name: 4list parrent parrent
        run: ls -l ../..

      - name: Run Python script
        run: python invest_sma_alert.py  # Specify the path to your Python script here
      - name: list files
        run: ls
