name: Run Python Script

on:
  schedule:
    - cron: '42 22 * * *' # Runs every day at midnight UTC
  push:
    branches:
      - main
      - test
#
jobs:
  invest_sma_alert:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'  # You can specify the Python version here
      - name: list files
        run: ls -l
      - name: cat data_invest.json
        run: cat data_invest.json
      - name: pip intall requirements.txt
        run: pip install -r requirements.txt
      - name: echovar
        run: echo "test01 is "$TEST01
      - name: Run Python script
        run: python invest_sma_alert.py  # Specify the path to your Python script here
      - name: list files
        run: ls
