name: Run Python Script

on:
  schedule:
    - cron: '35 22 * * *' # Runs every day at midnight UTC
  push:
    branches:
      - main
      - test
#
jobs:
  invest_sma_alert:
    runs-on: ubuntu-latest
    env:
      INVEST_LOGFILE : "history.log"
      FINANCIALMODELINGPREP_APIKEY: ${{ secrets.FINANCIALMODELINGPREP_APIKEY }}
      TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
      TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'  # You can specify the Python version here
      - name: list files
        run: ls -l
      - name: cat data_invest.json
        run: cat data_invest.json
      - name: pip install requirements.txt
        run: pip install -r requirements.txt
      - name: Run Python script
        run: python invest_sma_alert.py  # Specify the path to your Python script here
      - name: list files
        run: ls
        env:
          GIT_AUTHOR_NAME: GitHub Actions
          GIT_AUTHOR_EMAIL: actions@github.com
          GIT_COMMITTER_NAME: GitHub Actions
          GIT_COMMITTER_EMAIL: actions@github.com
      - name: push changes to remote
        run: |
          git config --global user.name "user mane"
          git config --global user.email "user email"
          git add history.log 
          git commit -m "push history"
          git push


#      - name: Commit and Push changes
##        uses: stefanzweifel/git-auto-commit-action@v4
#        with:
#          commit_message: "Add history.log from GitHub Actions"
#          branch: main
#          file_pattern: history.log
